[package]
name = 'legs'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'legs'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
ansi-to-tui = "8.0.0"
color-eyre = "0.6.5"
extendr-api = '0.9.0'
ratatui = { version = "0.30.2", features = ["crossterm"] }
strip-ansi-escapes = "0.2.1"

[profile.release]
lto = true
codegen-units = 1
