# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib legs, .registration = TRUE
NULL

#' Render a dataframe inside a full terminal view.
#' @export
view_df <- function(df) .Call(wrap__view_df, df)

# nolint end
